<a href="https://colab.research.google.com/github/Mouly22/DataScience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import *
arr = array([2,3,46,24])
print(arr)


[ 2  3 46 24]


In [ ]:
import numpy as np


In [ ]:
a = np.array([[1, 2, 3, 5,4,5], [2, 4, 6,6,7, 5]])
print(a)

[[1 2 3 5 4 5]
 [2 4 6 6 7 5]]


In [ ]:
#get a specific element:

print(a[1, -2])

6


In [ ]:
#get a specific row:
print(a[0, :])


[1 2 3 5]


In [ ]:
#get a specofic column:
print(a[:, 1])

[2 4]


In [ ]:
print(a[0, 1:4:2 ])            #you have to write step here using colon(the last two is actually stepsize)

[2 5]


In [ ]:
#3D 
p = np.array([[[2,4], [6,4]],[[3,6],[2,1]]])
print(p)

[[[2 4]
  [6 4]]

 [[3 6]
  [2 1]]]


In [ ]:
#get specific element from that 3D:
print(p[0,1,1])     #eikhane uporer matrix access korle 0 r nicher matrix access korle 1; so 0 and 1. then matrix access korar pore row access, then specific value access

4


In [ ]:
#replace:
p[1,1,0] = 30        #replace one specific value
print(p)


[[[ 2  4]
  [45 34]]

 [[ 3  1]
  [30  4]]]


In [ ]:
#replace one whole row:
p[0,0,:] = [4, 16]
print(p)

[[[ 4 16]
  [45 34]]

 [[ 3  1]
  [30  4]]]


In [ ]:
#replace one whole column:
p[0,:,0] = [5 , 10]
print(p)

[[[ 5 16]
  [10 34]]

 [[ 3  1]
  [30  4]]]


In [ ]:
#replace multiple rows:
p[:,0,:] = [4, 16]
print(p)

[[[ 4 16]
  [10 34]]

 [[ 4 16]
  [30  4]]]


In [ ]:
#all 0's matrix:
y = np.zeros([])
print(y)

0.0


In [ ]:
np.full_like(p,[99,99])

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [ ]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.random.rand(4,2,3)

array([[[0.30496744, 0.3062453 , 0.5265015 ],
        [0.62309017, 0.69033531, 0.27870371]],

       [[0.48826039, 0.93666445, 0.59799756],
        [0.08316071, 0.54384134, 0.10590305]],

       [[0.51495122, 0.30689182, 0.3388829 ],
        [0.43870796, 0.85413872, 0.5868281 ]],

       [[0.05493099, 0.96449811, 0.14544826],
        [0.58477071, 0.45198122, 0.70305976]]])

In [ ]:
arr = np.array([[1,3,2]])
r2 = np.repeat(arr, 3, axis= 0)
print(r2)

[[1 3 2]
 [1 3 2]
 [1 3 2]]
